# fly.toml app configuration file generated for ai-prd-generator

app = 'ai-prd-generator'
primary_region = 'sjc'

[build]

[env]
  PORT = '8000'
  PYTHON_VERSION = '3.12'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = '10s'
    interval = '30s'
    method = 'GET'
    timeout = '5s'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
